name: Production Deploy
on: 
  push:
    branches: [ master ]
  workflow_dispatch:
  
jobs:
  web-deploy:
    name: FTP Deploy Action
    runs-on: ubuntu-latest
    steps:
    - name: Get Latest Code
      uses: actions/checkout@v2

    # Here is the deployment action
    - name: Upload from public_html via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: ${{ secrets.PROD_FTP_HOST }}
        username: ${{ secrets.PROD_FTP_USERNAME }}
        password: ${{ secrets.PROD_FTP_PASSWORD }}
        local_dir: "./public_html"